import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// on importe le composant Link de next,
// il resemble au composant Link de react-router
// mais il attend un prop "href" et non "to" pour specifier l'url
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Ometeo Next",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div>
					<nav>
						<Link className="m-4" href={"/"}>
							Accueil
						</Link>
						<Link className="m-4" href={"/contact"}>
							Contact
						</Link>
					</nav>
					{children}
				</div>
			</body>
		</html>
	);
}
